# Generated by Django 3.0.2 on 2020-02-25 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OrgUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.TextField(blank=True, max_length=120)),
                ('department', models.TextField(blank=True, max_length=120)),
                ('is_admin', models.BooleanField()),
                ('is_employee', models.BooleanField()),
            ],
        ),
    ]
