# Generated by Django 3.0.2 on 2020-01-20 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgusers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orguser',
            name='organisation',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='orguser',
            name='username',
            field=models.TextField(),
        ),
    ]
