# Generated by Django 3.0.2 on 2020-02-25 10:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('organisations', '0001_initial'),
        ('orgusers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orguser',
            name='_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='orguser',
            name='organisation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organisation', to='organisations.Organisation'),
        ),
    ]
