# Generated by Django 3.0.2 on 2020-01-21 08:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organisations', '0001_initial'),
        ('orgusers', '0003_auto_20200120_1157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orguser',
            name='organisation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organisation', to='organisations.Organisation'),
        ),
    ]
