# Generated by Django 3.0.2 on 2020-01-26 07:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orgusers', '0004_auto_20200121_0834'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orguser',
            name='username',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
