# Generated by Django 3.0.2 on 2020-01-26 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orgusers', '0005_auto_20200126_0701'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orguser',
            old_name='username',
            new_name='_user',
        ),
    ]
