# Generated by Django 3.0.2 on 2020-02-09 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgusers', '0006_auto_20200126_0714'),
    ]

    operations = [
        migrations.AddField(
            model_name='orguser',
            name='department',
            field=models.TextField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='orguser',
            name='job_title',
            field=models.TextField(blank=True, max_length=120),
        ),
    ]
