# Generated by Django 3.0.2 on 2020-02-09 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisation',
            name='address_line1',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='organisation',
            name='address_line2',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='organisation',
            name='country',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='organisation',
            name='logo',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='organisation',
            name='postcode',
            field=models.CharField(blank=True, max_length=18),
        ),
        migrations.AddField(
            model_name='organisation',
            name='suburb',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='description',
            field=models.TextField(blank=True, max_length=120),
        ),
    ]
