# Generated by Django 3.0.2 on 2020-02-11 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisations', '0002_auto_20200209_0350'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisation',
            name='state',
            field=models.CharField(blank=True, max_length=80),
        ),
    ]
