# Generated by Django 3.0.2 on 2020-01-30 00:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0001_initial'),
        ('bookings', '0002_booking_resource'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='resource',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resource', to='resources.Resource'),
        ),
    ]
