# Generated by Django 3.0.2 on 2020-02-13 06:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orgusers', '0007_auto_20200209_0350'),
        ('bookings', '0003_auto_20200130_0057'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='organizer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='organizer', to='orgusers.OrgUser'),
        ),
    ]
